#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=debugq
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=16
#SBATCH --time=1:00:00
#SBATCH --output=./out/slurm-%j.out

module load python3
cd '/home/dpirvu/axion/'

python3 ./out/script30.py >> ./out/output30.txt &
python3 ./out/script31.py >> ./out/output31.txt &
python3 ./out/script32.py >> ./out/output32.txt &
python3 ./out/script33.py >> ./out/output33.txt &
python3 ./out/script34.py >> ./out/output34.txt &
wait
